# 使用 Node.js 官方映像作为基础映像
FROM node:14

# 设置工作目录
WORKDIR /app

# 复制应用程序文件到工作目录
COPY package.json package-lock.json ./
RUN npm install

# 复制应用程序源代码
COPY . .

# 暴露端口
EXPOSE 3000

# 启动应用程序
CMD ["node", "app.js"]
