name: build
on:
  push:
    branches:
      - v0.0
  pull_request:
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: "Image build and signed"
        SLACK_MESSAGE: |
          Name: gengyanrui
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'HIGH'
        format: 'table'
        output: 'report.txt'
        exit: 1

    - name: upload to slack
      uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: xoxb-5828957891927-5846920816146-MAMo5SZfdkgSEyjaONh4cVh9 
        content: 'file content'
        file_type: 'text'
        file_name: 'report.txt'
        title: 'failed scan'
        initial_comment: 'post by slack-upload-file'

    # - name: Run Trivy vulnerability scanner in IaC mode
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     scan-type: 'fs'
    #     severity: 'CRITCAL'


      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'