name: build
on:
  push:
    branches:
      - v0.0
  pull_request:
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: "Image build and signed"
        SLACK_MESSAGE: |
          Name: gengyanrui
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'CRITICAL'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'